CONTROL_PLANE_COUNT := "1"
WORKER_COUNT := "3"

# lists all available recipes
list:
    @just --list --unsorted

# spins up a local cluster
up:
    TALOSCONFIG=talos-config KUBECONFIG=kube-config talosctl cluster create docker \
      --name talos \
      --state .talos \
      --workers {{ WORKER_COUNT }} \
      --config-patch @patches/common.yaml \
      --config-patch-controlplanes @patches/control-planes.yaml

# tears down the cluster
down:
    TALOSCONFIG=talos-config talosctl cluster destroy \
      --name talos \
      --state .talos
    rm -f kube-config talos-config

# patches all machines
apply-all MODE="auto": (apply-control-planes MODE) (apply-workers MODE)

# patches all control planes
apply-control-planes MODE="auto":
    #!/usr/bin/env sh
    for i in $(seq 1 {{ CONTROL_PLANE_COUNT }})
    do
      just apply-control-plane "$i" "{{ MODE }}"
    done

# patches all workers
apply-workers MODE="auto":
    #!/usr/bin/env sh
    for i in $(seq 1 {{ WORKER_COUNT }})
    do
      just apply-worker "$i" "{{ MODE }}"
    done

# patches one control plane
apply-control-plane N MODE="auto":
    TALOSCONFIG=talos-config talosctl patch machineconfig \
      --cluster talos \
      --nodes talos-controlplane-{{ N }} \
      --mode {{ MODE }} \
      --patch @patches/common.yaml \
      --patch @patches/control-planes.yaml

# patches one worker
apply-worker N MODE="auto":
    TALOSCONFIG=talos-config talosctl patch machineconfig \
      --cluster talos \
      --nodes talos-worker-{{ N }} \
      --mode {{ MODE }} \
      --patch @patches/common.yaml
