apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: talos-cloud-controller-manager
    repo: oci://ghcr.io/siderolabs/charts
    version: 0.4.2
    releaseName: talos-cloud-controller-manager
    namespace: kube-system
    includeCRDs: true
    valuesInline:
      useDaemonSet: true
      # features:
      #   # required when using ipv6 stack, otherwise ccm picks hetzner's cgnat ip address..
      #   preferIPv6: true
patches:
  - path: patch-config-map.yaml
