apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: talos-cloud-controller-manager
  repo: oci://ghcr.io/siderolabs/charts
  version: 0.4.1
  releaseName: talos-cloud-controller-manager
  namespace: kube-system
  includeCRDs: true
  valuesInline:
    useDaemonSet: true
    # features:
    #   preferIPv6: true
patches:
  - path: patch-config-map.yaml
