apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/experimental-install.yaml
helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    # version: 1.17.0-pre.3
    version: 1.16.4
    releaseName: cilium
    namespace: kube-system
    includeCRDs: true
    apiVersions:
      - gateway.networking.k8s.io/v1/GatewayClass
      # - monitoring.coreos.com/v1
    valuesInline:
      defs:
        hubble: &hubble false
        ipv6: &ipv6 true
        ipv4: &ipv4 false
        rollout: &rollout true
        serviceMonitor: &serviceMonitor
          serviceMonitor:
            enabled: false
            interval: 60s

      # debug:
      #   enabled: true

      routingMode: native

      k8sServiceHost: "localhost"
      k8sServicePort: 7445

      ipam:
        mode: kubernetes

      kubeProxyReplacement: true

      ipv6:
        enabled: *ipv6
      ipv4:
        enabled: *ipv4

      k8s:
        requireIPv6PodCIDR: *ipv6
        requireIPv4PodCIDR: *ipv4

      enableIPv6Masquerade: false
      enableIPv4Masquerade: false

      enableIPv6BIGTCP: *ipv6
      enableIPv4BIGTCP: *ipv4

      autoDirectNodeRoutes: false
      directRoutingSkipUnreachable: false

      # ipv6NativeRoutingCIDR: "fc00:1::/96"

      localRedirectPolicy: false

      hostFirewall:
        enabled: false

      endpointRoutes:
        enabled: false

      externalIPs:
        enabled: true

      nodePort:
        enabled: true
        bindProtection: false

      hostPort:
        enabled: true

      l7Proxy: true

      bgpControlPlane:
        enabled: false
        announce:
          loadbalancerIP: true

      nat46x64Gateway:
        enabled: false

      nodeIPAM:
        enabled: false

      bpf:
        # datapathMode: veth
        datapathMode: netkit
        masquerade: false
        tproxy: false
        hostLegacyRouting: false

      bandwidthManager:
        enabled: true
        bbr: true

      # native causes the following error
      # interface kubespan: attaching program cil_xdp_entry using bpf_link: create link: operation not supported
      # loadBalancer:
      #   acceleration: native
      loadBalancer:
        acceleration: best-effort

      authentication:
        enabled: false
        mutual:
          spire:
            enabled: false

      encryption:
        enabled: false
        type: wireguard
        nodeEncryption: false # broken

      gatewayAPI:
        enabled: true
        hostNetwork:
          enabled: true

      socketLB:
        enabled: true

      # defaultLBServiceIPAM: nodeipam
      kubeProxyReplacementHealthzBindAddr: "[::]:10256"

      rollOutCiliumPods: *rollout

      operator:
        replicas: 1
        rollOutPods: *rollout
        prometheus:
          enabled: true
          <<: *serviceMonitor

      hubble:
        enabled: *hubble
        enableOpenMetrics: true
        metrics:
          enabled:
            - dns
            - drop
            - tcp
            - flow
            - icmp
            - port-distribution
            - http
          <<: *serviceMonitor
        relay:
          enabled: *hubble
          rollOutPods: *rollout
          prometheus:
            <<: *serviceMonitor
        ui:
          enabled: *hubble
          rollOutPods: *rollout
          service:
            annotations:
              omni-kube-service-exposer.sidero.dev/port: "50080"
              omni-kube-service-exposer.sidero.dev/label: Hubble
      envoy:
        enabled: true
        rollOutPods: *rollout
        prometheus:
          <<: *serviceMonitor
        securityContext:
          capabilities:
            keepCapNetBindService: true
            envoy:
              - NET_BIND_SERVICE
              - NET_ADMIN
              - SYS_ADMIN
              - BPF

      prometheus:
        enabled: true
        <<: *serviceMonitor

      securityContext:
        privileged: true
        capabilities:
          ciliumAgent:
            - CHOWN
            - KILL
            - NET_ADMIN
            - NET_RAW
            - IPC_LOCK
            - SYS_ADMIN
            - SYS_RESOURCE
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
          cleanCiliumState:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_RESOURCE
      cgroup:
        autoMount:
          enabled: false
        hostRoot: /sys/fs/cgroup
# patches:
#   - path: patch-namespaces.yaml
