apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/experimental-install.yaml
helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    # version: 1.17.0-pre.3
    version: 1.16.4
    releaseName: cilium
    namespace: kube-system
    includeCRDs: true
    apiVersions:
      - gateway.networking.k8s.io/v1/GatewayClass
      # - monitoring.coreos.com/v1
    valuesInline:
      # debug:
      #   enabled: true

      routingMode: native

      k8sServiceHost: "localhost"
      k8sServicePort: 7445

      ipam:
        mode: kubernetes

      kubeProxyReplacement: true

      ipv6:
        enabled: true
      ipv4:
        enabled: false

      k8s:
        requireIPv6PodCIDR: true
        requireIPv4PodCIDR: false

      enableIPv6Masquerade: false
      enableIPv4Masquerade: false

      enableIPv6BIGTCP: true
      enableIPv4BIGTCP: false

      autoDirectNodeRoutes: false
      directRoutingSkipUnreachable: false

      localRedirectPolicy: false

      hostFirewall:
        enabled: false

      endpointRoutes:
        enabled: false

      externalIPs:
        enabled: true

      nodePort:
        enabled: true
        bindProtection: false

      hostPort:
        enabled: true

      l7Proxy: true

      bgpControlPlane:
        enabled: false
        announce:
          loadbalancerIP: true

      nat46x64Gateway:
        enabled: false

      nodeIPAM:
        enabled: false

      bpf:
        datapathMode: veth
        masquerade: false
        tproxy: false
        hostLegacyRouting: false

      bandwidthManager:
        enabled: true
        bbr: true

      authentication:
        enabled: false
        mutual:
          spire:
            enabled: false

      encryption:
        enabled: false
        type: wireguard
        nodeEncryption: false

      gatewayAPI:
        enabled: true
        hostNetwork:
          enabled: true

      # defaultLBServiceIPAM: nodeipam
      kubeProxyReplacementHealthzBindAddr: "[::]:10256"

      rollOutCiliumPods: true

      operator:
        replicas: 1
        rollOutPods: true
        prometheus:
          enabled: true
          serviceMonitor:
            enabled: false
            interval: 60s

      hubble:
        enabled: true
        enableOpenMetrics: true
        metrics:
          enabled:
            - dns
            - drop
            - tcp
            - flow
            - icmp
            - port-distribution
            - http
          serviceMonitor:
            enabled: false
            interval: 60s
        relay:
          enabled: true
          rollOutPods: true
          prometheus:
            serviceMonitor:
              enabled: false
              interval: 60s
        ui:
          enabled: true
          rollOutPods: true
          service:
            annotations:
              omni-kube-service-exposer.sidero.dev/port: "50080"
              omni-kube-service-exposer.sidero.dev/label: Hubble
      envoy:
        enabled: true
        rollOutPods: true
        prometheus:
          serviceMonitor:
            enabled: false
            interval: 60s
        securityContext:
          capabilities:
            keepCapNetBindService: true
            envoy:
              - NET_BIND_SERVICE
              - NET_ADMIN
              - SYS_ADMIN
              - BPF
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: false
          interval: 60s

      securityContext:
        privileged: true
        capabilities:
          ciliumAgent:
            - CHOWN
            - KILL
            - NET_ADMIN
            - NET_RAW
            - IPC_LOCK
            - SYS_ADMIN
            - SYS_RESOURCE
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
          cleanCiliumState:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_RESOURCE
      cgroup:
        autoMount:
          enabled: false
        hostRoot: /sys/fs/cgroup
# patches:
#   - path: patch-namespaces.yaml
