apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    cloud.google.com/workload-identity-provider: "projects/603494906590/locations/global/workloadIdentityPools/talos/providers/talos-oidc"
    cloud.google.com/service-account-email: "cert-manager@miran248-talos-modules-dev.iam.gserviceaccount.com"
    cloud.google.com/audience: "sts.googleapis.com"
    cloud.google.com/gcloud-run-as-user: "1001"
    cloud.google.com/injection-mode: "direct"
    # cloud.google.com/injection-mode: "gcloud"
