apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: scaleway-csi
    repo: https://helm.scw.cloud/
    version: 0.2.1
    releaseName: scaleway-csi
    namespace: kube-system
    includeCRDs: true
    valuesInline:
      controller:
        replicaCount: 1
        priorityClassName: "system-cluster-critical"
        nodeSelector:
          provider: scaleway
        scaleway:
          existingSecretName: scaleway
      node:
        priorityClassName: "system-node-critical"
        nodeSelector:
          kubernetes.io/os: linux
          provider: scaleway
