@build:
  just build-helm talos-cloud-controller-manager
  just build-helm cilium-ip6
  just build-helm cilium-ip4
  just build-helm iperf

build-helm NAME:
  kustomize build --enable-helm {{ NAME }} > {{ NAME }}.yaml
