@build:
  just build-helm talos-cloud-controller-manager
  just build-helm cilium
  just build-helm hcloud-csi
  just build-helm iperf

build-helm NAME:
  kustomize build --enable-helm {{ NAME }} > {{ NAME }}.yaml
