@build:
  just build-helm cilium
  just build-helm hcloud-ccm
  just build-helm hcloud-csi
  just build-helm iperf
  just build-helm talos-ccm

build-helm NAME:
  kustomize build --enable-helm {{ NAME }} > {{ NAME }}.yaml
