apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app-argocd.yaml
patches:
  - path: patch-argocd-cm.yaml
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 7.6.12
    releaseName: argocd
    namespace: argocd
    includeCRDs: true
    valuesInline:
      dex:
        enabled: false
