apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
patches:
  - path: patch-argocd-cm.yaml
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 7.8.21
    releaseName: argocd
    namespace: argocd
    includeCRDs: true
    valuesInline:
      dex:
        enabled: false
      configs:
        params:
          server.insecure: "true"
