init:
  packer init .

hcloud:
  packer build hcloud.pkr.hcl

TMP_FILE_PATH := "./tmp-scaleway/talos-1.13.3-amd64"

scaleway:
  # https://docs.siderolabs.com/talos/v1.13/platform-specific-installations/cloud-platforms/scaleway
  # https://factory.talos.dev/?arch=amd64&platform=scaleway&schematic-id=18d0321d7fb289f707a76e1deeaa5c97e62209722cbf4bc533a5d51eb666885f&target=cloud&version=1.13.3
  mkdir -p ./tmp-scaleway
  wget "https://factory.talos.dev/image/18d0321d7fb289f707a76e1deeaa5c97e62209722cbf4bc533a5d51eb666885f/v1.13.3/scaleway-amd64.raw.zst" -O {{ TMP_FILE_PATH }}.raw.zst
  zstd -d {{ TMP_FILE_PATH }}.raw.zst -o {{ TMP_FILE_PATH }}.raw
  qemu-img convert -O qcow2 {{ TMP_FILE_PATH }}.raw {{ TMP_FILE_PATH }}.qcow2
  rclone copy {{ TMP_FILE_PATH }}.qcow2 scaleway:miran248-terraform-talos-modules-dev-images

TALOS_SRC := "/Users/miran/projects/github/talos"
DEV_IMAGE_SRC := TALOS_SRC + "/_out/scaleway-amd64.raw.zst"
DEV_IMAGE_TAG := "v1.14.0-alpha.1-dev.7"
TMP_DEV_FILE_PATH := "./tmp-scaleway/v1.14.0-alpha.1-dev.7"

scaleway-dev:
  cd {{ TALOS_SRC }} && make docker-imager USERNAME=miran TAG={{ DEV_IMAGE_TAG }} DEST=_out PUSH=false TARGET_ARGS="--no-cache"
  docker rmi ghcr.io/miran/imager:{{ DEV_IMAGE_TAG }} 2>/dev/null || true
  docker load --input {{ TALOS_SRC }}/_out/imager.tar
  rm -f {{ DEV_IMAGE_SRC }} {{ TMP_DEV_FILE_PATH }}.raw {{ TMP_DEV_FILE_PATH }}.qcow2
  docker run --rm -v /dev:/dev -v {{ TALOS_SRC }}/_out:/out --privileged ghcr.io/miran/imager:{{ DEV_IMAGE_TAG }} scaleway --arch amd64
  mkdir -p ./tmp-scaleway
  zstd -d {{ DEV_IMAGE_SRC }} -o {{ TMP_DEV_FILE_PATH }}.raw
  qemu-img convert -O qcow2 {{ TMP_DEV_FILE_PATH }}.raw {{ TMP_DEV_FILE_PATH }}.qcow2
  rclone copy {{ TMP_DEV_FILE_PATH }}.qcow2 scaleway:miran248-terraform-talos-modules-dev-images
