apply:
  terraform init -upgrade
  terraform apply -auto-approve

destroy:
  #!/usr/bin/env bash
  rm *talos-config
  rm *kube-config
  terraform destroy -auto-approve

# > just config single6
config PREFIX:
  terraform output --raw "{{ PREFIX }}_talos_config" > "{{ PREFIX }}-talos-config"
  TALOSCONFIG="{{ PREFIX }}-talos-config" talosctl -n 192.168.1.11 kubeconfig "{{ PREFIX }}-kube-config"
