apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: google
spec:
  provider:
    gcpsm:
      projectID: miran248-talos-modules-dev
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hcloud
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: google
  data:
    - secretKey: token
      remoteRef:
        key: hcloud
