apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcloud-csi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: infra
  source:
    path: manifests/hcloud-csi
    repoURL: https://github.com/miran248/terraform-talos-modules.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
