apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
patches:
  - path: patch-deployment.yaml
helmCharts:
  - name: gcp-workload-identity-federation-webhook
    repo: https://pfnet-research.github.io/gcp-workload-identity-federation-webhook
    version: 0.4.5
    releaseName: gcp-wif-webhook
    namespace: gcp-wif-webhook-system
    includeCRDs: true
    valuesInline:
      nameOverride: gcp-wif-webhook
      controllerManager:
        manager:
          args:
            - --token-default-mode=0444
