apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-wif-webhook-controller-manager
  namespace: gcp-wif-webhook-system
spec:
  template:
    spec:
      containers:
        - name: manager
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        - name: kube-rbac-proxy
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
