apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: hcloud-cloud-controller-manager
    repo: https://charts.hetzner.cloud
    version: 1.23.0
    releaseName: hcloud-ccm
    namespace: kube-system
    includeCRDs: true
    valuesInline:
      nameOverride: hcloud-ccm
      networking:
        enabled: false
